import {
  UserProfile,
  Group,
  KarmaSubmission,
  KarmaReview,
  KarmaRecord,
  AppNotification,
  Announcement,
  EventSettings,
  AuditLog,
} from '../types';

export const INITIAL_EVENT_SETTINGS: EventSettings = {
  id: 'stride_2027',
  event_name: 'STRIDE',
  tagline: 'Explore. Build. Learn. Earn Karma.',
  registration_start: '2027-07-20T00:00:00+05:30',
  registration_end: '2027-08-22T23:59:59+05:30',
  event_start: '2027-08-25T00:00:00+05:30',
  event_end: '2027-09-05T23:59:59+05:30',
  qualification_karma: 3000,
  timezone: 'Asia/Kolkata',
  maximum_groups: 500,
  default_group_capacity: 500,
  is_submissions_open_override: null,
  is_registration_open_override: null,
  min_volunteers_per_group: 1,
  max_volunteers_per_group: 4,
};

export const INITIAL_GROUPS: Group[] = [
  {
    id: 'grp-alpha',
    name: 'Group Alpha',
    capacity: 500,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:00:00+05:30',
  },
  {
    id: 'grp-beta',
    name: 'Group Beta',
    capacity: 500,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:05:00+05:30',
  },
  {
    id: 'grp-gamma',
    name: 'Group Gamma',
    capacity: 500,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:10:00+05:30',
  },
  {
    id: 'grp-delta',
    name: 'Group Delta',
    capacity: 400,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:15:00+05:30',
  },
  {
    id: 'grp-epsilon',
    name: 'Group Epsilon',
    capacity: 350,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:20:00+05:30',
  },
  {
    id: 'grp-001',
    name: 'Group 001 (Tech Innovators)',
    capacity: 300,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:25:00+05:30',
  },
  {
    id: 'grp-002',
    name: 'Group 002 (Code Voyagers)',
    capacity: 300,
    status: 'ACTIVE',
    created_at: '2027-07-01T10:30:00+05:30',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-superadmin-1',
    auth_user_id: 'auth-superadmin-1',
    full_name: 'Johnathan Archer',
    email: 'admin.john@stride.mulearn.org',
    phone: '+91 98765 43210',
    college: 'Apex Institute of Technology',
    branch: 'Computer Science & Engineering',
    semester: 'Staff / Admin',
    student_id: 'ADM-2027-01',
    mulearn_username: 'superjohn',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    registration_id: 'STRIDE-ADMIN-001',
    created_at: '2027-07-01T08:00:00+05:30',
    updated_at: '2027-07-01T08:00:00+05:30',
  },
  {
    id: 'usr-admin-1',
    auth_user_id: 'auth-admin-1',
    full_name: 'Sneha Varghese',
    email: 'sneha.admin@stride.mulearn.org',
    phone: '+91 98765 43211',
    college: 'Model Engineering College',
    branch: 'Information Technology',
    semester: 'Staff / Admin',
    student_id: 'ADM-2027-02',
    mulearn_username: 'snehav_stride',
    role: 'ADMIN',
    status: 'ACTIVE',
    registration_id: 'STRIDE-ADMIN-002',
    created_at: '2027-07-05T09:00:00+05:30',
    updated_at: '2027-07-05T09:00:00+05:30',
  },
  {
    id: 'usr-mod-1',
    auth_user_id: 'auth-mod-1',
    full_name: 'Kiran Das',
    email: 'kiran.mod@stride.mulearn.org',
    phone: '+91 98765 43212',
    college: 'Government Engineering College, Barton Hill',
    branch: 'Electronics & Communication',
    semester: 'Staff / Moderator',
    student_id: 'MOD-2027-01',
    mulearn_username: 'kirandas_m',
    role: 'MODERATOR',
    status: 'ACTIVE',
    registration_id: 'STRIDE-MOD-001',
    created_at: '2027-07-08T10:00:00+05:30',
    updated_at: '2027-07-08T10:00:00+05:30',
  },
  {
    id: 'usr-vol-1',
    auth_user_id: 'auth-vol-1',
    full_name: 'Alex Mathew',
    email: 'alex.mathew@mulearn.org',
    phone: '+91 94471 23456',
    college: 'TKM College of Engineering',
    branch: 'Computer Science',
    semester: 'Semester 5',
    student_id: 'VOL-TKM-2024-88',
    mulearn_username: 'alex_mathew_mu',
    role: 'VOLUNTEER',
    status: 'ACTIVE',
    registration_id: 'STRIDE-VOL-00142',
    created_at: '2027-07-15T11:00:00+05:30',
    updated_at: '2027-07-15T11:00:00+05:30',
    assigned_group_ids: ['grp-alpha', 'grp-beta'],
  },
  {
    id: 'usr-vol-2',
    auth_user_id: 'auth-vol-2',
    full_name: 'Priya George',
    email: 'priya.george@mulearn.org',
    phone: '+91 94471 98765',
    college: 'College of Engineering Trivandrum',
    branch: 'Electrical & Electronics',
    semester: 'Semester 5',
    student_id: 'VOL-CET-2024-19',
    mulearn_username: 'priya_george_cet',
    role: 'VOLUNTEER',
    status: 'ACTIVE',
    registration_id: 'STRIDE-VOL-00143',
    created_at: '2027-07-16T12:00:00+05:30',
    updated_at: '2027-07-16T12:00:00+05:30',
    assigned_group_ids: ['grp-gamma'],
  },
  {
    id: 'usr-stud-1',
    auth_user_id: 'auth-stud-1',
    full_name: 'Rahul Nair',
    email: 'rahul.nair27@gmail.com',
    phone: '+91 98460 11223',
    college: 'Mar Athanasius College of Engineering',
    branch: 'Computer Science & Engineering',
    semester: 'Semester 1',
    student_id: 'MACE27CS042',
    mulearn_username: 'rahul_nair_mace',
    role: 'STUDENT',
    status: 'ACTIVE',
    registration_id: 'STRIDE-2027-00101',
    group_id: 'grp-alpha',
    created_at: '2027-07-21T09:30:00+05:30',
    updated_at: '2027-07-21T09:30:00+05:30',
  },
  {
    id: 'usr-stud-2',
    auth_user_id: 'auth-stud-2',
    full_name: 'Ananya Sharma',
    email: 'ananya.sharma@gmail.com',
    phone: '+91 98460 22334',
    college: 'Muthoot Institute of Technology and Science',
    branch: 'Artificial Intelligence & Data Science',
    semester: 'Semester 1',
    student_id: 'MITS27AD019',
    mulearn_username: 'ananya_codes',
    role: 'STUDENT',
    status: 'ACTIVE',
    registration_id: 'STRIDE-2027-00102',
    group_id: 'grp-alpha',
    created_at: '2027-07-21T10:15:00+05:30',
    updated_at: '2027-07-21T10:15:00+05:30',
  },
  {
    id: 'usr-stud-3',
    auth_user_id: 'auth-stud-3',
    full_name: 'Devika Menon',
    email: 'devika.menon@gmail.com',
    phone: '+91 98460 33445',
    college: 'Rajagiri School of Engineering & Technology',
    branch: 'Electronics & Computer Engineering',
    semester: 'Semester 1',
    student_id: 'RSET27EC088',
    mulearn_username: 'devika_menon',
    role: 'STUDENT',
    status: 'ACTIVE',
    registration_id: 'STRIDE-2027-00103',
    group_id: 'grp-beta',
    created_at: '2027-07-22T11:00:00+05:30',
    updated_at: '2027-07-22T11:00:00+05:30',
  },
  {
    id: 'usr-stud-4',
    auth_user_id: 'auth-stud-4',
    full_name: 'Kavya Suresh',
    email: 'kavya.suresh@gmail.com',
    phone: '+91 98460 44556',
    college: 'NSS College of Engineering',
    branch: 'Mechanical Engineering',
    semester: 'Semester 1',
    student_id: 'NSS27ME012',
    mulearn_username: 'kavya_suresh',
    role: 'STUDENT',
    status: 'ACTIVE',
    registration_id: 'STRIDE-2027-00104',
    group_id: 'grp-gamma',
    created_at: '2027-07-23T14:20:00+05:30',
    updated_at: '2027-07-23T14:20:00+05:30',
  },
  {
    id: 'usr-stud-5',
    auth_user_id: 'auth-stud-5',
    full_name: 'Rohan Thomas',
    email: 'rohan.thomas@gmail.com',
    phone: '+91 98460 55667',
    college: 'Saintgits College of Engineering',
    branch: 'Robotics & Automation',
    semester: 'Semester 1',
    student_id: 'SGC27RA005',
    mulearn_username: 'rohan_robotics',
    role: 'STUDENT',
    status: 'ACTIVE',
    registration_id: 'STRIDE-2027-00105',
    group_id: 'grp-alpha',
    created_at: '2027-07-24T16:00:00+05:30',
    updated_at: '2027-07-24T16:00:00+05:30',
  },
];

export const INITIAL_SUBMISSIONS: KarmaSubmission[] = [
  // Student 1 (Rahul Nair) - 3450 Karma (Qualified!)
  {
    id: 'sub-001',
    student_id: 'usr-stud-1',
    student_name: 'Rahul Nair',
    student_email: 'rahul.nair27@gmail.com',
    student_mulearn: 'rahul_nair_mace',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Setup GitHub & Markdown Profile',
    mulearn_task_link: 'https://app.mulearn.org/tasks/intro-github-markdown-401',
    claimed_karma: 800,
    description: 'Created custom GitHub README profile with dynamic widgets and markdown formatting as outlined in the μJourney starter quest.',
    proof_url: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'github_profile_proof.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-25T10:00:00+05:30',
    updated_at: '2027-08-25T16:30:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-001-v',
        submission_id: 'sub-001',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Clean implementation, profile link verified on μLearn.',
        reviewed_at: '2027-08-25T14:10:00+05:30',
      },
      {
        id: 'rev-001-a',
        submission_id: 'sub-001',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Verified on GitHub and μLearn database. Karma granted.',
        reviewed_at: '2027-08-25T16:30:00+05:30',
      },
    ],
  },
  {
    id: 'sub-002',
    student_id: 'usr-stud-1',
    student_name: 'Rahul Nair',
    student_email: 'rahul.nair27@gmail.com',
    student_mulearn: 'rahul_nair_mace',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Build First HTML/CSS Portfolio',
    mulearn_task_link: 'https://app.mulearn.org/tasks/web-portfolio-foundation-502',
    claimed_karma: 1200,
    description: 'Designed and deployed a responsive personal portfolio website hosted on GitHub Pages with responsive navigation and contact form.',
    proof_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'portfolio_deployment.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-26T11:20:00+05:30',
    updated_at: '2027-08-26T18:00:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-002-v',
        submission_id: 'sub-002',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Live URL checked and CSS structure validated.',
        reviewed_at: '2027-08-26T15:00:00+05:30',
      },
      {
        id: 'rev-002-a',
        submission_id: 'sub-002',
        reviewer_id: 'usr-superadmin-1',
        reviewer_name: 'Johnathan Archer',
        reviewer_role: 'SUPER_ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Top quality submission. 1200 Karma credited.',
        reviewed_at: '2027-08-26T18:00:00+05:30',
      },
    ],
  },
  {
    id: 'sub-003',
    student_id: 'usr-stud-1',
    student_name: 'Rahul Nair',
    student_email: 'rahul.nair27@gmail.com',
    student_mulearn: 'rahul_nair_mace',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Discord Community Onboarding & Peer Introduction',
    mulearn_task_link: 'https://app.mulearn.org/tasks/community-onboarding-101',
    claimed_karma: 1450,
    description: 'Completed the μLearn Discord introductory quests, engaged in the first-year interest group, and attended the live kick-off orientation.',
    proof_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'discord_intro_karma.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-27T09:40:00+05:30',
    updated_at: '2027-08-27T14:15:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-003-v',
        submission_id: 'sub-003',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Verified in Discord server.',
        reviewed_at: '2027-08-27T12:00:00+05:30',
      },
      {
        id: 'rev-003-a',
        submission_id: 'sub-003',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Approved. Student reaches 3,450 Karma and achieves qualification status!',
        reviewed_at: '2027-08-27T14:15:00+05:30',
      },
    ],
  },

  // Student 2 (Ananya Sharma) - 2650 Karma Verified + 600 Pending Admin + 350 Pending Volunteer
  {
    id: 'sub-004',
    student_id: 'usr-stud-2',
    student_name: 'Ananya Sharma',
    student_email: 'ananya.sharma@gmail.com',
    student_mulearn: 'ananya_codes',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Python Foundations & Data Challenge',
    mulearn_task_link: 'https://app.mulearn.org/tasks/python-basics-301',
    claimed_karma: 1500,
    description: 'Completed 15 algorithmic exercises and submitted clean, documented Python scripts with test cases.',
    proof_url: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'python_exercises_completed.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-25T14:00:00+05:30',
    updated_at: '2027-08-26T10:00:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-004-v',
        submission_id: 'sub-004',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Code submitted in GitHub repo, tests passing.',
        reviewed_at: '2027-08-25T18:00:00+05:30',
      },
      {
        id: 'rev-004-a',
        submission_id: 'sub-004',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Verified and approved.',
        reviewed_at: '2027-08-26T10:00:00+05:30',
      },
    ],
  },
  {
    id: 'sub-005',
    student_id: 'usr-stud-2',
    student_name: 'Ananya Sharma',
    student_email: 'ananya.sharma@gmail.com',
    student_mulearn: 'ananya_codes',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Git Branching & Collaboration Quest',
    mulearn_task_link: 'https://app.mulearn.org/tasks/git-collab-quest-402',
    claimed_karma: 1150,
    description: 'Created PRs, resolved merge conflicts, and tagged releases in a simulated multi-collaborator open source repo.',
    proof_url: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'git_pull_request_merged.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-27T08:30:00+05:30',
    updated_at: '2027-08-27T16:00:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-005-v',
        submission_id: 'sub-005',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Great PR workflow demonstrated.',
        reviewed_at: '2027-08-27T11:00:00+05:30',
      },
      {
        id: 'rev-005-a',
        submission_id: 'sub-005',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: '1,150 Karma credited. Total now 2,650.',
        reviewed_at: '2027-08-27T16:00:00+05:30',
      },
    ],
  },
  {
    id: 'sub-006',
    student_id: 'usr-stud-2',
    student_name: 'Ananya Sharma',
    student_email: 'ananya.sharma@gmail.com',
    student_mulearn: 'ananya_codes',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Open Source Contribution to μLearn Repos',
    mulearn_task_link: 'https://app.mulearn.org/tasks/os-contribution-601',
    claimed_karma: 600,
    description: 'Submitted documentation fix and translated getting started guide to regional language.',
    proof_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'pr_translation_merged.png',
    status: 'PENDING_ADMIN_REVIEW',
    submitted_at: '2027-08-28T09:00:00+05:30',
    updated_at: '2027-08-28T11:30:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-006-v',
        submission_id: 'sub-006',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'PR #182 merged upstream by core team. Approved for Admin review.',
        reviewed_at: '2027-08-28T11:30:00+05:30',
      },
    ],
  },

  // Student 3 (Devika Menon) - 600 Verified + 1 Rejected Submission
  {
    id: 'sub-007',
    student_id: 'usr-stud-3',
    student_name: 'Devika Menon',
    student_email: 'devika.menon@gmail.com',
    student_mulearn: 'devika_menon',
    group_id: 'grp-beta',
    group_name: 'Group Beta',
    task_name: 'μJourney: Command Line & Terminal Mastery',
    mulearn_task_link: 'https://app.mulearn.org/tasks/cli-basics-201',
    claimed_karma: 600,
    description: 'Practiced bash scripting, file navigation, permissions, and created automated build script.',
    proof_url: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'cli_terminal_proof.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-26T14:00:00+05:30',
    updated_at: '2027-08-26T20:00:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-007-v',
        submission_id: 'sub-007',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Terminal output verified.',
        reviewed_at: '2027-08-26T17:00:00+05:30',
      },
      {
        id: 'rev-007-a',
        submission_id: 'sub-007',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Verified.',
        reviewed_at: '2027-08-26T20:00:00+05:30',
      },
    ],
  },
  {
    id: 'sub-008',
    student_id: 'usr-stud-3',
    student_name: 'Devika Menon',
    student_email: 'devika.menon@gmail.com',
    student_mulearn: 'devika_menon',
    group_id: 'grp-beta',
    group_name: 'Group Beta',
    task_name: 'μJourney: UI/UX Wireframe in Figma',
    mulearn_task_link: 'https://app.mulearn.org/tasks/figma-design-305',
    claimed_karma: 800,
    description: 'Designed a 3-page mobile app mockup for community recycling.',
    proof_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'figma_mockup_lowres.png',
    status: 'REJECTED',
    submitted_at: '2027-08-27T10:00:00+05:30',
    updated_at: '2027-08-27T15:30:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-008-v',
        submission_id: 'sub-008',
        reviewer_id: 'usr-vol-1',
        reviewer_name: 'Alex Mathew',
        reviewer_role: 'VOLUNTEER',
        decision: 'REJECT',
        stage: 'VOLUNTEER',
        reason: 'The Figma share link is set to private. Please change share settings to "Anyone with the link can view" and resubmit with full artboards.',
        reviewed_at: '2027-08-27T15:30:00+05:30',
      },
    ],
  },

  // Student 4 (Kavya Suresh) - 2400 Karma Verified
  {
    id: 'sub-009',
    student_id: 'usr-stud-4',
    student_name: 'Kavya Suresh',
    student_email: 'kavya.suresh@gmail.com',
    student_mulearn: 'kavya_suresh',
    group_id: 'grp-gamma',
    group_name: 'Group Gamma',
    task_name: 'μJourney: IoT & Arduino Sensor Simulation',
    mulearn_task_link: 'https://app.mulearn.org/tasks/iot-tinkercad-arduino-701',
    claimed_karma: 2400,
    description: 'Built a multi-sensor climate telemetry simulation on Tinkercad with LCD readout and buzzer alerts.',
    proof_url: 'https://images.unsplash.com/photo-1553406830-ef2513450d76?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'tinkercad_circuit_diagram.png',
    status: 'VERIFIED',
    submitted_at: '2027-08-26T16:00:00+05:30',
    updated_at: '2027-08-27T11:00:00+05:30',
    resubmission_count: 0,
    reviews: [
      {
        id: 'rev-009-v',
        submission_id: 'sub-009',
        reviewer_id: 'usr-vol-2',
        reviewer_name: 'Priya George',
        reviewer_role: 'VOLUNTEER',
        decision: 'APPROVE',
        stage: 'VOLUNTEER',
        reason: 'Circuit logic and Tinkercad project verified.',
        reviewed_at: '2027-08-26T19:00:00+05:30',
      },
      {
        id: 'rev-009-a',
        submission_id: 'sub-009',
        reviewer_id: 'usr-admin-1',
        reviewer_name: 'Sneha Varghese',
        reviewer_role: 'ADMIN',
        decision: 'APPROVE',
        stage: 'ADMIN',
        reason: 'Exceptional project work. 2,400 Karma verified.',
        reviewed_at: '2027-08-27T11:00:00+05:30',
      },
    ],
  },
  // Pending Volunteer Submission for Volunteer Alex to test approving
  {
    id: 'sub-010',
    student_id: 'usr-stud-5',
    student_name: 'Rohan Thomas',
    student_email: 'rohan.thomas@gmail.com',
    student_mulearn: 'rohan_robotics',
    group_id: 'grp-alpha',
    group_name: 'Group Alpha',
    task_name: 'μJourney: Competitive Coding Sprint #1',
    mulearn_task_link: 'https://app.mulearn.org/tasks/competitive-coding-sprint-801',
    claimed_karma: 950,
    description: 'Solved 8 algorithmic challenge problems on LeetCode/μJourney sprint track with optimal time complexity.',
    proof_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&auto=format&fit=crop&q=60',
    proof_filename: 'leetcode_sprint_solutions.png',
    status: 'PENDING_VOLUNTEER_REVIEW',
    submitted_at: '2027-08-28T12:00:00+05:30',
    updated_at: '2027-08-28T12:00:00+05:30',
    resubmission_count: 0,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'usr-stud-1',
    title: '🎉 Qualification Achieved!',
    message: 'Congratulations Rahul! You have achieved 3,450 Verified Karma and crossed the 3,000 Karma threshold to qualify for STRIDE 2027 completion recognition.',
    type: 'achievement',
    read: false,
    created_at: '2027-08-27T14:15:00+05:30',
  },
  {
    id: 'notif-2',
    user_id: 'usr-stud-1',
    title: 'Karma Verified: +1,450 Karma',
    message: 'Your submission for "μJourney: Discord Community Onboarding" was verified by Admin Sneha Varghese.',
    type: 'success',
    read: true,
    created_at: '2027-08-27T14:15:00+05:30',
  },
  {
    id: 'notif-3',
    user_id: 'usr-stud-2',
    title: 'Volunteer Approved Submission',
    message: 'Volunteer Alex Mathew approved your task "Open Source Contribution". It has moved to Stage 2 Admin Verification.',
    type: 'info',
    read: false,
    created_at: '2027-08-28T11:30:00+05:30',
  },
  {
    id: 'notif-4',
    user_id: 'usr-stud-3',
    title: 'Submission Requires Attention',
    message: 'Your task "UI/UX Wireframe in Figma" was rejected by Volunteer Alex Mathew: The Figma share link is set to private.',
    type: 'error',
    read: false,
    created_at: '2027-08-27T15:30:00+05:30',
  },
  {
    id: 'notif-5',
    user_id: 'usr-vol-1',
    title: 'New Task Submission in Group Alpha',
    message: 'Rohan Thomas submitted "Competitive Coding Sprint #1" (950 Karma) for your review.',
    type: 'info',
    read: false,
    created_at: '2027-08-28T12:00:00+05:30',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: '🚀 STRIDE 2027 is Live — Explore μJourney Quests!',
    content: 'Welcome all first-year innovators to STRIDE 2027! Over the next 12 days, explore exciting μJourney quests, build real-world projects, earn Karma, and collaborate with your group peers and assigned volunteers.',
    priority: 'urgent',
    created_by: 'usr-superadmin-1',
    created_by_name: 'Johnathan Archer',
    published_at: '2027-08-25T00:00:00+05:30',
    status: 'PUBLISHED',
  },
  {
    id: 'ann-2',
    title: '⚡ Group Alpha Leads the Karma Board',
    content: 'Huge shoutout to Group Alpha and their assigned volunteer Alex Mathew for crossing 6,100 total verified Karma on day 3 of the challenge!',
    priority: 'high',
    created_by: 'usr-admin-1',
    created_by_name: 'Sneha Varghese',
    published_at: '2027-08-27T18:00:00+05:30',
    status: 'PUBLISHED',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    actor_id: 'usr-superadmin-1',
    actor_name: 'Johnathan Archer',
    actor_role: 'SUPER_ADMIN',
    action: 'INITIALIZE_EVENT',
    target_type: 'SETTING',
    target_id: 'stride_2027',
    details: 'Configured STRIDE 2027 event parameters and qualification threshold (3,000 Karma).',
    timestamp: '2027-07-01T08:00:00+05:30',
  },
  {
    id: 'log-2',
    actor_id: 'usr-admin-1',
    actor_name: 'Sneha Varghese',
    actor_role: 'ADMIN',
    action: 'CREATE_GROUP',
    target_type: 'GROUP',
    target_id: 'grp-alpha',
    details: 'Created Group Alpha with max student capacity 500.',
    timestamp: '2027-07-01T10:00:00+05:30',
  },
  {
    id: 'log-3',
    actor_id: 'usr-superadmin-1',
    actor_name: 'Johnathan Archer',
    actor_role: 'SUPER_ADMIN',
    action: 'ASSIGN_VOLUNTEER',
    target_type: 'GROUP',
    target_id: 'grp-alpha',
    details: 'Assigned Volunteer Alex Mathew to Group Alpha.',
    timestamp: '2027-07-15T11:15:00+05:30',
  },
  {
    id: 'log-4',
    actor_id: 'usr-vol-1',
    actor_name: 'Alex Mathew',
    actor_role: 'VOLUNTEER',
    action: 'VOLUNTEER_APPROVE_SUBMISSION',
    target_type: 'SUBMISSION',
    target_id: 'sub-001',
    details: 'Approved stage 1 for Rahul Nair (800 Karma).',
    timestamp: '2027-08-25T14:10:00+05:30',
  },
  {
    id: 'log-5',
    actor_id: 'usr-admin-1',
    actor_name: 'Sneha Varghese',
    actor_role: 'ADMIN',
    action: 'ADMIN_VERIFY_SUBMISSION',
    target_type: 'SUBMISSION',
    target_id: 'sub-001',
    details: 'Final admin verification completed for Rahul Nair (800 Karma added to ledger).',
    timestamp: '2027-08-25T16:30:00+05:30',
  },
];
